from enum import StrEnum


class DocumentVersionStatus(StrEnum):
    UPLOADED = "UPLOADED"
    HASHED = "HASHED"
    DUPLICATE_DETECTED = "DUPLICATE_DETECTED"
    STORED = "STORED"
    EXTRACTING = "EXTRACTING"
    EXTRACTED = "EXTRACTED"
    SEMANTIC_READY = "SEMANTIC_READY"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
