#requires -Version 5.1
<#
.SYNOPSIS
    Generate docker\.env and patch the Neo4j password in
    docker-compose.yml.

.DESCRIPTION
    Two artefacts come out of this script:

      1. A strong Neo4j password is written into both NEO4J_AUTH and
         KW_NEO4J_PASSWORD in docker-compose.yml. If the file still
         carries the upstream ``test_password_change_me`` placeholder
         the patch is applied; otherwise the existing password is
         kept (re-runs are idempotent).

      2. A docker\.env file is written with the LLM provider posture
         + the API keys you want passed through to the api container.
         The compose file references each of these as ``${VAR:-}`` so
         missing keys cause the relevant feature to stay disabled —
         no harm done.

    All keys are optional. The most common posture is:

        -GeminiKey <key>            # primary LLM (Gemini 2.5 Flash)
        -AnthropicKey <key>         # fallback LLM
        -VoyageKey <key>            # Phase 3 vector search

    Provider routing follows ADR-013 §6:

        auto       — Gemini wins when its key is set, else Anthropic
        gemini     — pin Gemini (refuses to wire if key missing)
        anthropic  — pin Anthropic (refuses to wire if key missing)

.PARAMETER Provider
    KW_LLM_PROVIDER value. Defaults to ``auto``.

.PARAMETER Neo4jPassword
    Neo4j credential. Pass as a SecureString (the script prompts when
    omitted). If docker-compose.yml has already been patched away
    from the placeholder, pass ``-SkipNeo4jPatch`` to keep it.

.PARAMETER GeminiKey, AnthropicKey, VoyageKey
    LLM / embeddings keys. SecureString — script prompts when
    omitted; pass empty string to clear.

.EXAMPLE
    .\20-Setup-Env.ps1 -Provider auto

    Prompts for every secret interactively, writes docker\.env, and
    patches the Neo4j password in docker-compose.yml.

.EXAMPLE
    .\20-Setup-Env.ps1 -SkipNeo4jPatch -Provider gemini

    Re-run after rotating only the LLM keys; leaves docker-compose.yml
    untouched.
#>
[CmdletBinding()]
param(
    [ValidateSet('auto', 'gemini', 'anthropic')]
    [string]$Provider = 'auto',

    [System.Security.SecureString]$Neo4jPassword,
    [System.Security.SecureString]$GeminiKey,
    [System.Security.SecureString]$AnthropicKey,
    [System.Security.SecureString]$VoyageKey,

    [string]$GeminiModel = '',
    [switch]$SkipNeo4jPatch
)

. "$PSScriptRoot\_lib.ps1"

function ConvertFrom-SecureStringToPlain([System.Security.SecureString]$secure) {
    if ($null -eq $secure) { return '' }
    $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try { [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr) }
    finally { [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }
}

function Read-OptionalSecret([string]$Prompt) {
    $value = Read-Host -Prompt "$Prompt (leave blank to skip)" -AsSecureString
    return $value
}

$repoRoot = Get-RepoRoot
$composeFile = Get-ComposeFile
$envFile = Get-DockerEnvFile

if (-not $SkipNeo4jPatch) {
    Write-Step "Patching Neo4j password in docker-compose.yml"
    if (-not $Neo4jPassword) {
        $Neo4jPassword = Read-Host -Prompt "Neo4j password (will replace 'test_password_change_me')" -AsSecureString
    }
    $plainNeo4j = ConvertFrom-SecureStringToPlain $Neo4jPassword
    if ([string]::IsNullOrEmpty($plainNeo4j)) {
        throw "Neo4j password cannot be empty. Re-run with a value or pass -SkipNeo4jPatch."
    }
    $compose = Get-Content $composeFile -Raw
    if ($compose.Contains('test_password_change_me')) {
        # ``String.Replace`` is a literal substitution — no regex
        # interpretation of the password value, so a ``$``-bearing
        # password won't accidentally inject a backreference.
        $compose = $compose.Replace('test_password_change_me', $plainNeo4j)
        Set-Content -Encoding UTF8 -Path $composeFile -Value $compose
        Write-Done "Neo4j password patched in $composeFile"
    } else {
        Write-Warn2 "Placeholder already replaced — leaving compose file alone."
    }
}

Write-Step "Writing $envFile"

# Prompt for any keys that weren't provided on the CLI.
if ($null -eq $GeminiKey)    { $GeminiKey    = Read-OptionalSecret 'Gemini API key (primary LLM)' }
if ($null -eq $AnthropicKey) { $AnthropicKey = Read-OptionalSecret 'Anthropic API key (fallback LLM)' }
if ($null -eq $VoyageKey)    { $VoyageKey    = Read-OptionalSecret 'Voyage API key (Phase 3 vector search)' }

$geminiPlain    = ConvertFrom-SecureStringToPlain $GeminiKey
$anthropicPlain = ConvertFrom-SecureStringToPlain $AnthropicKey
$voyagePlain    = ConvertFrom-SecureStringToPlain $VoyageKey

$lines = @(
    "# Generated by scripts\windows\20-Setup-Env.ps1 — do not commit (gitignored).",
    "KW_LLM_PROVIDER=$Provider",
    "GEMINI_API_KEY=$geminiPlain",
    "KW_GEMINI_MODEL=$GeminiModel",
    "ANTHROPIC_API_KEY=$anthropicPlain",
    "VOYAGE_API_KEY=$voyagePlain"
)
Set-Content -Encoding ASCII -Path $envFile -Value $lines

# Best-effort tighten ACL: only the current user can read.
try {
    $acl = Get-Acl $envFile
    $acl.SetAccessRuleProtection($true, $false)
    $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        $env:USERNAME, 'FullControl', 'Allow'
    )
    $acl.SetAccessRule($rule)
    Set-Acl -Path $envFile -AclObject $acl
} catch {
    Write-Warn2 "Could not tighten ACL on $envFile (continuing): $_"
}

Write-Done "Wrote $envFile"
Write-Host ""
Write-Step "Summary"
Write-Host "  KW_LLM_PROVIDER     : $Provider"
Write-Host ("  GEMINI_API_KEY      : " + ($(if ($geminiPlain) { 'set' } else { 'empty' })))
Write-Host ("  KW_GEMINI_MODEL     : " + ($(if ($GeminiModel) { $GeminiModel } else { '(SDK default — gemini-2.5-flash)' })))
Write-Host ("  ANTHROPIC_API_KEY   : " + ($(if ($anthropicPlain) { 'set' } else { 'empty' })))
Write-Host ("  VOYAGE_API_KEY      : " + ($(if ($voyagePlain) { 'set' } else { 'empty' })))
Write-Host ""
Write-Host "  Next: .\Start.ps1"
